# Generated by Django 6.0.6 on 2026-06-16 14:27

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=24)),
                ('expiration', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('tokens', django.db.models.manager.Manager()),
            ],
        ),
    ]
