# Generated by Django 6.0.6 on 2026-07-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.BinaryField(null=True),
        ),
    ]
