# Generated by Django 6.0.6 on 2026-06-17 02:43

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_authtokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=24)),
                ('expiration', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('tokens', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='AuthTokens',
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=44),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
