# Generated by Django 6.0.6 on 2026-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_password_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(max_length=44, primary_key=True, serialize=False),
        ),
    ]
