# Generated by Django 6.0.6 on 2026-06-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_authtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expiration',
            field=models.DateTimeField(),
        ),
    ]
