# Generated by Django 6.0.7 on 2026-07-13 07:16

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            managers=[
                ('chat_channels', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=24)),
                ('time_sent', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatchannel')),
            ],
            managers=[
                ('chats', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatChannelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
            managers=[
                ('chat_channel_groups', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='channel_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatchannelgroup'),
        ),
        migrations.CreateModel(
            name='FileChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('content_type', models.CharField(max_length=100)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
            ],
            managers=[
                ('file_chats', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TextChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
            ],
            managers=[
                ('text_chats', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VoiceChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatchannelgroup')),
            ],
            managers=[
                ('voice_channels', django.db.models.manager.Manager()),
            ],
        ),
    ]
