# Generated by Django 6.0.6 on 2026-06-16 14:03

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=24)),
                ('salt', models.CharField(max_length=24)),
                ('bio', models.CharField(default='', max_length=1024)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
    ]
